### PR TITLE
SAK-99 Kaltura upgrade to Sakai 11+

### PR DESCRIPTION
**Pull request by ern**

### CODE REVIEW

**Comment by gonenradai** [comment]
@ern - shouldn't this PR be into 11x branch, as we discussed last week?

**Comment by gonenradai** [comment]
@ern  - can you answer my question above?
I thought we wanted Sakai 11+ changes to be merged to the 11x branch, and Sakai 12 (which at the moment is represented by master branch) be merged to master...

**Comment by ottenhoff** [comment]
Hi @gonenradai I think it makes sense to merge into master, and then to merge the commit into 11.x. Sakai 12 will be released next year and then commits should be done against master and merged into a 12.x branch.

**Comment by gonenradai** [comment]
seems a bit redundant to maintain master + 11.x while master will be always equal to 11.x, and then master + 12.x while master will always be equal to 12.x...

**Comment by ottenhoff** [comment]
The Sakai community maintains two branches in addition to a master branch. Fixes often would need to go into master and then moved into the two maintenance branches after QA confirms the fixes.

**Comment by gonenradai** [comment]
so: 
* master = bleeding edge (i.e. includes bug fixes that are not approved/tested yet)
* 11x = latest stable version of 11x
* 10x = latest stable version of 10x
Is that right?

If this is the case, it means that this PR is right now merged to master and should be QA'ed, and only once approved we should merge into 11x (since this PR is only about 11x and not about 10x).

**Comment by ottenhoff** [comment]
Correct

**Pull request merged**
